---
title: "Module 8"
subtitle: "{{< var md-08.title >}}"
editor: source
params:
    module: 8
execute: 
  echo: false
  warning: false
---

## {{< fa bullseye >}} Learning Objectives

```{r}
#| label: setup

library(epoxy)
```

```{r}
#| label: learning-objectives

lobj <- readr::read_csv(here::here("data/tbl-01-rbtl-fs24-learning-objectives.csv")) |> 
  dplyr::filter(module == params$module) |>
  dplyr::pull(learning_objectives)

```

```{epoxy}
{1:length(lobj)}. {lobj[1:length(lobj)]}
```

## {{< fa display >}} Slides


[View slides in full screen](../slides/lec-08-waste-research.html) | [Download slides as PDF](https://github.com/rbtl-fs24/website/raw/main/slides/lec-08-waste-research.pdf)

```{=html}
<iframe class="slide-deck" src="../slides/lec-08-waste-research.html" height="420" width="747" style="border: 1px solid #123233;"></iframe>
```

## {{< fa book >}} Readings

- Add readings.
- Google Drive link.

## {{< fa code >}} Assignments

Please complete the following assignment by Wednesday, 24th April 2024. 

-   [Assignment 1](../assignments/md-08/am-08-1-presentation.qmd): 

