---
title: "Module 5"
subtitle: "{{< var md-05.title >}}"
editor: source
params:
    module: 5
execute: 
  echo: false
  warning: false
bibliography: references.bib
---

## {{< fa bullseye >}} Learning Objectives

```{r}
#| label: setup

library(epoxy)
```

```{r}
#| label: learning-objectives

lobj <- readr::read_csv(here::here("data/tbl-01-rbtl-fs24-learning-objectives.csv")) |> 
  dplyr::filter(module == params$module) |>
  dplyr::pull(learning_objectives)

```

```{epoxy}
{1:length(lobj)}. {lobj[1:length(lobj)]}
```

## {{< fa display >}} Slides

[View slides in full screen](../slides/lec-05-conditions.html) | [Download slides as PDF](https://github.com/rbtl-fs24/website/raw/main/slides/lec-05-conditions.pdf)

```{=html}
<iframe class="slide-deck" src="../slides/lec-05-conditions.html" height="420" width="747" style="border: 1px solid #123233;"></iframe>
```

## {{< fa book >}} Readings

1.  Read [R for Data Science - Section 16 - Factors](https://r4ds.hadley.nz/factors)
2.  Read [R for Data Science - Section 6 - Workflow: Scripts and projects](https://r4ds.hadley.nz/workflow-scripts)

## {{< fa code >}} Assignments

Please complete the following assignment by Wednesday, 27th March 2024. 

-   [Assignment 1](../assignments/md-05/am-05-1-survey-data.qmd): Complete survey of five peers and analyse data

Thank you for working through this assignment. 