---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Title

CVEN 5837: Special Topics - Data Analytics for Development

# Course Information

This course provides students with foundational skills in using the collection of R tidyverse packages as a tool for reproducible research and communication. Lectures will be delivered for students to learn how to write code through participatory live coding. We will use publicly available data related to waste management, air quality, and sanitation. Students will learn how to help themselves and others to build upon the obtained skills to apply them to their data analysis projects.

Topics include:

-   Overview of qualitative and quantitative research methods and tools
-   The data science lifecycle
-   Data organization in spreadsheets
-   Exploratory data anaylsis using visualisation
-   Concept of tidy data and data tidying
-   Data transformation and descriptive statistics
-   Data communcation using the Quarto open-source scientific and technical publishing system

# Learning Goals

1.  Be familiar with the most commonly used qualitative and quantitative data collection methods and tools.

2.  Be able to employ remote sensing and in-situ data, and analysis tools to illustrate the utility of solutions for water, agriculture, disaster forecasting and relief, air quality, and global health.

# Textbooks and Materials

We will rely entirely on open source and open access material for this course. We will use "R for Data Science" by Hadley Wickham, and "Tidyverse Skills for Data Science" by Carrie Wright, Shannon E. Ellis, Stephanie C. Hicks and Roger D. Peng, as complementary reading and learning material for this course. Additional readings will consist of blog posts, journal articles, and reports. All required readings will be provided through Canvas.

# Course Calendar

| week | day      | topic                                                                             |
|--------------|--------------|--------------------------------------------|
| 1    | July 5   | Welcome! & Data Science Lifecycle                                                 |
| 2    | July 12  | Exploratory data analysis using visualisation & Data organization in spreadsheets |
| 3    | July 19  | Data transformation and descriptive statistics                                    |
| 4    | July 26  | Concept of tidy data and data tidying                                             |
| 5    | August 2 | Data communcation using the Quarto                                                |
| 6    | August 9 | Exam                                                                              |

# Weekly Structure

|          |                                           |
|----------|-------------------------------------------|
| Monday   | Homework assignment is due                |
| Tuesday  | Lecture                                   |
| Wednesay | Feedback (grading) on quiz and assignment |
| Thursday | Student hours on Zoom                     |
| Friday   | Learning reflections are due              |


# Assignments

**Homework assignments**: Each week will have at least one homework assignment. These assignments are delivered as Quarto documents with instructions and some sample code. Students are required to submit their work through Canvas. Homework assignments are graded. The scoring will be presented on Canvas.

**Readings/Learning reflections**: Additional readings will be provided. Some are required, others are optional. Students will be asked to write 100 word reflections on the material that they have learned. These reflections are graded. Scoring  will be presented on Canvas. 

**Exam**: There is a practical 2-hour exam, which assesses the technical skills taught during the course. It contains programming exercises using the R programming language and you can use any material that you want. The success of the exam depends on the effort put into the compulsory homework assignments. 

# Attendance 

We hope you can participate in all classes. Class participation is an essential component for successful completion of this course. If you have a valid reason to miss a class, we expect you to inform us at least 12 hours before the beginning of the class. 

# Grading scheme 

Your overall course grade will be comprised of the following components, and their weights:

- Homework assignments: 40 points
- Learning reflections: 25 points
- Exam: 35 points

# Late work, extensions, and special circumstances

Due dates are set and all work is due on the stated date. This helps students to keep pace through the course and allow staff to return marks and feedback timely. Submission the due date might not always be possible when something gets in the way. We drop the lowest score for each of the assignments. That means you can miss one assignment and still achieve maximum score.

**Late work policy:**

-   Quizzes: Not accepted late

-   Homework assignments: Late work accepted up to 3 working days after the deadline (Tuesday after deadline, same time) with 10% penalty for each day

-   Project: Late work accepted up to 5 working days after the deadline, with 5% penalty for each day

**Special circumstances**

-   Documented reason why you are unable to to complete an assignment in the course

-   How are these decisions made?

    -   End of course

    -   External committee


