---
title: "Course Overview"
editor: source
execute: 
  echo: false
  warning: false
---

# data science for openwashdata course 001 

Instructor: [Lars Schöbitz](https://openwashdata.org/about/lars/)

Start: 2023-10-31
End: 2024-02-06

# Course Information

This course provides learners with skills in using the collection of R tidyverse packages as a tool for data analysis, reproducible research and communication. Lectures will be delivered through participatory live coding for students to learn how to write code in code-along exercises. We will use publicly available data related to waste management, air quality, and sanitation. Students will learn how to help themselves using large language models (LLMs) and AI tools Perplexity and build upon the obtained skills to apply them to their data analysis projects.

Topics include:

-   The data science life-cycle
-   Data organization in spreadsheets
-   Exploratory data analysis using visualization
-   Using AI for software development in R 
-   Concept of tidy data and data tidying
-   Data transformation and descriptive statistics
-   Data communication using the Quarto open-source scientific and technical publishing system

# Learning Goals

1. Be able to use a common set of data science tools (R, RStudio IDE, Git, GitHub, tidyverse, Quarto) to illustrate and communicate the results of data analysis projects.

2. Learn to use the Quarto file format and the RStudio IDE visual editing mode to produce scholarly documents with citations, footnotes, cross-references, figures, and tables.

# Textbooks and Materials

We will rely entirely on open source and open access material for this course. We will use "R for Data Science" by Hadley Wickham, and "Tidyverse Skills for Data Science" by Carrie Wright, Shannon E. Ellis, Stephanie C. Hicks and Roger D. Peng, as complementary reading and learning material for this course. Additional readings will consist of blog posts, journal articles, and reports. All required readings and class material will be provided through this website. 

# Course Calendar

```{r}
readr::read_csv("data/tbl-01-cven5837-ss23-course-schedule.csv") |> 
  dplyr::select(date, week, topic = title, note) |> 
  dplyr::mutate(date = format(date, format = "%d %B %Y")) |> 
  knitr::kable()
  
```

# Weekly Structure

|          |                                           |
|----------|-------------------------------------------|
| **Monday**   |                |
| **Tuesday**  |  Module from 2 pm to 4:30 pm CET                              |
| **Wednesday** | |
| **Thursday** | Student hours on Zoom (10 am to 12 pm CET) |
| **Friday**   |              |

# Assignments

**Homework assignments**: Each week will have at least one homework assignment. All assignments, but those for Week 1 are delivered as Quarto documents with instructions and some sample code. Students are required to submit their work through GitHub.

**Readings**: Every week, additional readings will be provided that support students in learning the underlying concept that are taught during the class.

**Capstone Project**: A final capstone project provides students with an opportunity to apply their skills and techniques to real-world data sets. Detailed instructions for the capstone project will be provided. The project will be delivered as Quarto documents and students are asked to submit their work through GitHub.

# Attendance 

We hope you can participate in all classes. Class participation is an important component for successful completion of this course.

# Code of Conduct 




