---
title: "Sign-up for data science for openwashdata course 001"
editor: source
execute: 
  echo: false
  warning: false
---

Thank you for your interest in this course. Your course instructors: [Lars Schöbitz](https://openwashdata.org/about/lars/) & [Mian Zhong](https://openwashdata.org/about/mian/) & [Sophia Skorik](https://openwashdata.org/about/sophia/) are looking forward to meet you. 

We will meet on Zoom for 10 modules over 15 weeks at the following times: 

- **Start:** 31st October 2023 - 2 pm to 4:30 pm CET 
- **End:** 6th February 2024 - 2 pm to 4:30 pm CET

This course teaches data science with R for people in the greater Water, Sanitation and Hygiene (WASH) sector. It is offered by offered by the [openwashdata academy](https://openwashdata.org/pages/academy/) with the mission to empower WASH professionals to engage with tools and workflows for open data and code. More details can be found on the [Course Overview](overview.html) page.

## {{< fa circle-question >}} How do I sign up? 

To sign up for the course, you need to complete the following four steps:

- Step 1: Get an account on GitHub
- Step 2: Register for an ORCID iD
- Step 3: Fill out our registration form
- Step 4: Register for the scheduled Zoom calls

### {{< fa brands github >}} Step 1: Get an account on GitHub

To set up an account on GitHub, follow these general steps:

1.  Go to the GitHub website at <https://github.com/>.
2.  Click on the "Sign up" button on the top right corner of the page.
3.  Enter your preferred username, email address, and password in the provided fields.
4.  Choose whether you want to receive updates and announcements via email.
5.  Complete the verification process by solving a puzzle and entering a verification code sent to your email.

::: {.callout-tip collapse="true"}
## Username advice from: [Happy Git and GitHub for the useR](https://happygitwithr.com/github-acct.html#github-acct)

You will be able to upgrade to a paid level of service, apply discounts, join organizations, etc. in the future, so don't fret about any of that now. **Except your username. You might want to give that some thought.**

A few tips, which sadly tend to contradict each other:

-   Incorporate your actual name! People like to know who they're dealing with. Also makes your username easier for people to guess or remember.
-   Reuse your username from other contexts, e.g., Twitter or Slack. But, of course, someone with no GitHub activity will probably be squatting on that.
-   Pick a username you will be comfortable revealing to your future boss.
-   Shorter is better than longer.
-   Be as unique as possible in as few characters as possible. In some settings GitHub auto-completes or suggests usernames.
-   Make it timeless. Don't highlight your current university, employer, or place of residence, e.g. JennyFromTheBlock.
-   Avoid words laden with special meaning in programming.
-   Avoid the use of upper vs. lower case to separate words. We highly recommend all lowercase. GitHub treats usernames in a case insensitive way, but using all lowercase is kinder to people doing downstream regular expression work with usernames, in various languages. A better strategy for word separation is to use a hyphen `-`.

You can change your username later, but better to get this right the first time.

-   <https://help.github.com/articles/changing-your-github-username/>
-   <https://help.github.com/articles/what-happens-when-i-change-my-username/>
:::

### {{< fa brands orcid >}} Step 2: Register for an ORCID iD

1. Create your ORCID iD at: <https://orcid.org/register>

[Learn more about ORCID and why you should get one](https://the-turing-way.netlify.app/communication/citable/citable-orcid.html?highlight=orcid), even if your are not a researcher or working in academia.

### {{< fa pen-clip >}} Step 3: Fill out our registration form

- Fill out this form: <https://forms.gle/JvPfVubntbaDrNZQ8>

### {{< fa headset >}} Step 4: Register for the scheduled Zoom meetings

- Register here: <https://ethz.zoom.us/meeting/register/u5EsdO6vqjkqGtBNj9qCUXVOXy8hPobo3hI2>

## Thanks for signing up!

You will hear from us with more details a week before the start of the course.

