---
title: "Week 1"
subtitle: "Get ready for the course!"
editor: source
params:
    week: 1
execute: 
  echo: false
  warning: false
bibliography: references.bib
---

```{=html}
<script defer data-domain="cven5837-ss23.github.io/website" src="https://plausible.io/js/plausible.js"></script>
```
This first week will be used to get you set up for the course. Work through the homework assignments one after the other.

## Learning Objectives

```{r}

lobj1 <- readr::read_csv(here::here("data/tbl-02-cven5837-ss23-learning-objectives.csv")) |> 
  dplyr::filter(week == params$week) |>
  dplyr::pull(learning_objectives)

```

1.  `r lobj1[1]`
2.  `r lobj1[2]`
3.  `r lobj1[3]`

## Readings

`r emo::ji("book")` Read the [Course Overview](../index.html) and pay special attention to the sections Assignments, Grading scheme, and late work.

`r emo::ji("book")` Read @wilson2017 "Good enough practices in scientific computing".

## Homework assignments

These homework assigments are pre-requisities for Week 2 of the. Complete them by **Friday, 9th June** to receive the points for this assignment.

### Prepare questions

`r emo::ji("book")` Read the [Course Overview](../index.html) and pay special attention to the sections **Assignments, Grading scheme, and Late Work**. Prepare at least one question.

### Get an account for GitHub

To set up an account on GitHub, follow these general steps:

1.  Go to the GitHub website at <https://github.com/>.
2.  Click on the "Sign up" button on the top right corner of the page.
3.  Enter your preferred username, email address, and password in the provided fields.
4.  Choose whether you want to receive updates and announcements via email.
5.  Complete the verification process by solving a puzzle and entering a verification code sent to your email.

::: callout-tip
## Username advice from: [Happy Git and GitHub for the useR](https://happygitwithr.com/github-acct.html#github-acct)

You will be able to upgrade to a paid level of service, apply discounts, join organizations, etc. in the future, so don't fret about any of that now. **Except your username. You might want to give that some thought.**

A few tips, which sadly tend to contradict each other:

-   Incorporate your actual name! People like to know who they're dealing with. Also makes your username easier for people to guess or remember.
-   Reuse your username from other contexts, e.g., Twitter or Slack. But, of course, someone with no GitHub activity will probably be squatting on that.
-   Pick a username you will be comfortable revealing to your future boss.
-   Shorter is better than longer.
-   Be as unique as possible in as few characters as possible. In some settings GitHub auto-completes or suggests usernames.
-   Make it timeless. Don't highlight your current university, employer, or place of residence, e.g. JennyFromTheBlock.
-   Avoid words laden with special meaning in programming.
-   Avoid the use of upper vs. lower case to separate words. We highly recommend all lowercase. GitHub treats usernames in a case insensitive way, but using all lowercase is kinder to people doing downstream regular expression work with usernames, in various languages. A better strategy for word separation is to use a hyphen `-`.

You can change your username later, but better to get this right the first time.

-   <https://help.github.com/articles/changing-your-github-username/>
-   <https://help.github.com/articles/what-happens-when-i-change-my-username/>
:::

### Log into Posit Cloud with GitHub account

Here are the instructions to login to Posit Cloud using a GitHub account:

1.  Go to the Posit Cloud Sign Up page: <https://login.posit.cloud/register>
2.  Click on the **"Sign Up with GitHub"** button.
3.  Enter your GitHub username and password when prompted.
4.  If this is your first time logging in to Posit Cloud with your GitHub account, you will be prompted to authorize Posit Cloud to access your GitHub account information.
5.  Once you have authorized access, you will be redirected back to the Posit Cloud website and logged in to your account.

Note that you will need to have a GitHub account in order to use this login method. If you do not have a GitHub account, you will need to create one before you can log in to Posit Cloud.

### Join the course workspace on Posit Cloud

-   Open this link: <https://posit.cloud/spaces/381404/join?access_code=5uSGb1oKtIngQmhbsM-th5J23j2SqMU2oIuX0go->

### Set up a GitHub Personal Access Token

Here are the step-by-step instructions to set up a GitHub personal access token:

1.  Log in to your GitHub account.
2.  Click on your profile picture in the top-right corner of the page.
3.  Select "Settings" from the dropdown menu.
4.  In the left sidebar, click on "Developer settings".
5.  Click on "Personal access tokens".
6.  Click on **"Tokens (classic)"**.
7.  Click on "Generate new token" and from the dropdown menu select **"Generate new token (classic)".**
8.  In the "Note" field, give your token the name: GITHUB_PAT
9.  Under Expiration, select "No expiration"
10. Under "Select scopes", select: **repo, workflow, user**
11. Click on "Generate token".
12. Your personal access token will be displayed on the screen. Copy it and store it in a safe place.

Remember to treat your access tokens like passwords and keep them secure (e.g. a password manager software).

### Fill out the pre-course survey

-   Survey link: <https://forms.gle/MSA4wcEHxNXJk5ef9>

### Open an issue on GitHub

-   Open the issue tracker on the website repository: <https://github.com/cven5873-ss23/website/issues>.
-   Click on "New issue" button.
-   In the "Title" field
    -   write: "Homework assignments for week 1 completed".
-   In the "Leave a comment" field,
    -   tag the course instructor with using the `@` sign in combination with `larnsce` as the username,
    -   post your question that you prepared after reading the [Course Overview](../index.html),
    -   add anything that you would like to add.

## Thanks! `r emo::ji("sunflower")`

Thank you for working through these assignments. I am looking forward to meeting you next week.
