---
title: "Documentation for your capstone project"
execute:
  echo: true
  warning: false
---

::: {.callout-important}
## Have you created a repository for your capstone project?
A pre-requisite for this homework is that you worked created a repository for your capstone project. This was an assignment of module 5. If you haven't yet, please work through the steps outlined in [Assignment 2 of Module 4](../md-05/am-05-1-project-data.qmd) before you start with the steps outlined here.
:::

## Step 1: Create a new folder

1. Open your capstone project on posit.cloud.

2. Navigate to the Files tab in the bottom right window of RStudio.

3. Click on the `data` folder in the bottom wight window.

4. Click on the "Folder" button to create a new folder.

5. Enter the name "processed" in field and click OK.

6. Click on the new `processed` folder in the bottom right window.

## Step 2: Create a `README.md` file

1. Navigate to the Files tab in the bottom right window of RStudio.

2. Click on the `data` folder in the bottom wight window.

3. Click on the `processed` folder in the bottom wight window.

4. Click on the "Blank File" button to create a new file.

5. Select the option "Text file".

6. Enter the name "README.md" in field and click OK.

7. Go to: <https://raw.githubusercontent.com/ds4owd-001/metadata-readme-template/main/README.md>

8. Copy the content that's displayed in your browser and paste it into the `README.md` file you have just created.

## Step 3: Create a `dictionary.xlsx`

1. Use a spreadsheet tool your choice and create a file called `dictionary.xlsx`.

2. Add two column names to the spreadsheet: `variable_name` and `description`. You do not need to describe all variables, yet.

3. Also save file as a `dictionary.csv` file.

## Step 4: Upload the dictionary 

1. Open your capstone project on posit.cloud.

2. Use the Files tab in the bottom right window to upload the data dictionary to the `data/processed` folder.

## Step 5: Prepare your analysis-read (processed) data

::: callout-important
## We will re-iterate on this step several times.

This step will involve several iterations, depending on the complexity of your raw data. Important is that you do this for a first time for this homework assignment, so that we can start evaluating the complexity of your propject.
:::
 
1. Open the `index.qmd` file in your capstone project.

2. Add a code chunk and write `library(tidyverse)` to load the R packages you have learned to work with.

3. Import your data by writing the following inside another code chunk (in this example we are using a CSV file):

```{r}
#| eval: false
read_csv(here::here("data/raw/your-file-name.csv"))
```

4. Write code to bring your data into a state where it's ready for analysis (e.g. rename columns, select columns that are relevant for your analysis, remove NAs, join several dataframes, etc.)

5. Once you have your data in a state where it's ready for analysis, save it as a CSV file in the `data/processed` folder.

## Step 6: Commit and push your changes 

1. Navigate to the Git pane in the top-right window of RStudio
2. Check the box next to all files to stage them for a commit
3. Click on the "Commit" button
4. Enter a commit message in the "Commit message" field
5. Click on the "Commit" button
6. Click on the "Push" button
7. Enter your GitHub username and GitHub Personal Access Token (PAT) in the "Username" and "Password" fields

::: callout-important
## Do not use your GitHub password

You need to enter the GitHub Personal Access Token (PAT) you created in Step 1 to push your changes back to GitHub.
:::

## Step 6: Open an issue on GitHub

1. Open [github.com](https://github.com/) in your browser.
2. Navigate to the GitHub organisation for the course.
3. Find the repository samples- that ends with your GitHub username.
4. Click on the "Issues" tab.
5. Click on the green "New issue" button.
6. In the "Title" field write: "Prepared first iteration of analysis-ready (processed) data".
7. In the "Leave a comment" field, tag the course instructors @larnsce @mianzg @sskorik01

