---
title: "Working with R, RStudio on Posit Cloud"
---

### Log into Posit Cloud with GitHub account

Here are the instructions to login to Posit Cloud using a GitHub account:

1.  Go to the Posit Cloud Sign Up page: <https://login.posit.cloud/register>
2.  Click on the **"Sign Up with GitHub"** button.
3.  Enter your GitHub username and password when prompted.
4.  If this is your first time logging in to Posit Cloud with your GitHub account, you will be prompted to authorize Posit Cloud to access your GitHub account information.
5.  Once you have authorized access, you will be redirected back to the Posit Cloud website and logged in to your account.

Note that you will need to have a GitHub account in order to use this login method. If you do not have a GitHub account, you will need to create one before you can log in to Posit Cloud.

### Join the course workspace on Posit Cloud

-   Open this link: <https://posit.cloud/spaces/484002/join?access_code=VQqBWZMZpA364I1KAvJfoepjZ8Ek0h_TOfNEkq-o>
