---
output: 
  word_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# README

This folder contains tables used for the course "CVEN 5837-005: Data Collection and Analysis Tools" offered at Colorado University, Boulder. This README file provides a description of the purpose for each table and a data dictionary of the contained variables.

## tab-01-cven-data-tools-course-overview

### Description

This table contains the course overview, including a title, a teaser (subtitle) and three specific learning objectives for each lecture.

### Variables

| **variable**        | **description**                              |
|---------------------|----------------------------------------------|
| date                | Date in YYYY-MM-DD                           |
| week                | Numeric value for number of week             |
| title               | Title of the lecture                         |
| teaser              | A one sentence teaser for the lecture        |
| lecturer            | Name of the lecturer                         |
| learning_objectives | Learning objectives for the specific lecture |

## tab-02-cven-data-tools-course-readings

### Description

This table contains the readings for the course. The variable 'type' helps to categorize the individual readings, which ensures a balanced selection of resources. The variable 'category' is added to declare if the reading is 'required' (e.g. for an assignment) or 'optional' as further reading.

### Variables

| **variable** | **description**                                                                    |
|----------|--------------------------------------------------------------------------------|
| week     | Numeric value for number of week                                               |
| title    | Title of the reading                                                           |
| type     | The type of material (e.g. journal article, book, slides, documentation, etc.) |
| category | Two possible values: optional/required                                         |
| link     | Hyperlink to the material (if applicable)                                      |

## tab-03-cven-data-tools-assignments

### Description

This table contains the assignments for the course.

### Variables

| **variables**         | **description**                                                          |
|-------------------|----------------------------------------------------------------------|
| week              | Numeric value for number of week                                     |
| title             | Title of the assignment                                              |
| type              | Type of assignment (e.g. homework, project, quiz, feedback, etc.)    |
| submission_format | How to submit the assignment. Can be a description or a direct link. |
| due               | The due date in format YYYY-MM-DD                                    |
| link              | Hyperlink to the material (if applicable)                            |
