---
title: "Module 4 - Assignment 1"
subtitle: "Data organization in spreadsheets"
bibliography: "../../rbtl-fs24.bib"
---

This course introduces learners to tools and workflows for data science with R. Learners are also introduced to the concept of collaborative writing and coding using git and GitHub within the context of reproducible documents (i.e. Quarto). So far we have used data that is well structured and ready to be used. However, in reality a lot of data entry and storage is still managed in spreadsheets. This is why we also touch on some (research) data management topics (Data Organization in Spreadsheet).

The reading for this assignment provides guidance for data entry and storage aspects. It offers practical recommendations for organizing spreadsheet data to reduce errors and ease later analyses.

## Task 1: Read and prepare examples

For this assignment, we ask you to:

1. Read @broman2018data: ["Data organization in spreadsheets"](https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989). 
2. Chose two of the recommendations and come up with [real-world examples]{.highlight-yellow} or scenarios where the recommendations could be applied in your work.
3. Be prepared to share these examples and [explain how the recommendations would improve your workflows]{.highlight-yellow}. This will be in a class setting as part of small discussion group (max 3 people).

## Task 2: Apply the recommendations to your samples data from Module 3

::: {.callout-important}
## Have you completed the assignments for module 3?
A pre-requisite for this homework is that you worked through the "Spreadsheet" assignment of module 3. If you have not done so, please do this first. https://rbtl-fs24.github.io/website/assignments/md-03/am-03-2-spreadsheet.html
:::

1. Open the rbtl-fs24 workspace on [posit.cloud](https://posit.cloud/spaces/484002/content/all?sort=name_asc)
2. Re-open your `samples-USERNAME` repository.
3. Create a new .R file and save it as `data_cleaning.R`.
4. Add `library(tidyverse)` to the top of the file.
5. Add `library(googlesheets4)` to the top of the file.
6. Use the `read_sheet()` function to read in your Google Sheets spreadsheet and store it in an object called `samples`.
7. Use the `glimpse()` function to inspect the data.
8. Try to use R functions to apply the recommendations from the reading to your data. Note down recommendations that you struggled to achieve.

### Example

The following is an example of a dataset that follows the recommendations from the reading. 

```{r}
#| echo: false
#| warning: false 
readr::read_csv("data/tbl-01-faecal-sludge-analysis.csv") |> 
  knitr::kable()
```

## Task 3: Create new folders

1. Navigate to the Files tab in the bottom right window of RStudio.
2. Click on the "Folder" button.
3. Enter the name "data" in field and click OK.
4. Click on the new `data` folder in the bottom right window.
5. Click on the "Folder" button.
6. Enter the name "processed" in field and click OK.
7. Click on the new `processed` folder in the bottom right window.

## Task 4: Write processed data

Once you comp...


