---
title: "Data pivoting"
---

## Step 1: Clone your module 6 assignments repository

1. Open github.com in your browser and navigate to the GitHub organisation for the course (or use your bookmark).
2. Find the repository md-06-assignments-USERNAME that ends with your GitHub username, and open it.
3. Click on the green "Code" button.
4. Copy the HTTPS URL to your clipboard.
5. Open the rbtl-fs24 workspace on [posit.cloud](https://posit.cloud/spaces/484002/content/all?sort=name_asc)
6. Click New Project > New Project from Git Repository
7. Paste the HTTPS URL from GitHub into the "URL of your Git Repository" field.
8. Wait until the project is deployed.
9. Open `md-06a-pivoting.qmd` and follow the instructions to work through the tasks.

## Step 2: Commit and push your changes 

The below is also described in `md-06a-pivoting.qmd`.

1. Navigate to the Git pane in the top-right window of RStudio
2. Check the box next to all files to stage them for a commit
3. Click on the "Commit" button
4. Enter a commit message in the "Commit message" field
5. Click on the "Commit" button
6. Click on the "Push" button
7. Enter your GitHub username and GitHub Personal Access Token (PAT) in the "Username" and "Password" fields

::: callout-important
## Do not use your GitHub password

You need to enter the GitHub Personal Access Token (PAT) you created in Step 1 to push your changes back to GitHub.
:::

## Step 3: Open an issue on GitHub

1. Open [github.com](https://github.com/) in your browser.
2. Navigate to the GitHub organisation for the course.
3. Find the repository md-06-assignments that ends with your GitHub username.
4. Click on the "Issues" tab.
5. Click on the green "New issue" button.
6. In the "Title" field write: "Completed module 6 assignments".
7. In the "Leave a comment" field, tag the course instructor @larnsce 

